services:
  postgres:
    image: postgres:15.3
    container_name: course-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: coursedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - course-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:7.3
    container_name: course-pgadmin
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - course-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: course-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9100:9100"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/coursedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - course-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  course-network:
    driver: bridge